### ISSUE TITLE
Add requirements

### ISSUE THREAD

**Issue by Noe-Imeji** [tmeedend/ac-mod-generator#1]
Hello,
Thank you for the very useful tool. I have managed to use it, however, there is some information missing in the description of the tool to make it work properly.
In the prerequisites, QuickBMS is missing and the need to modify the paths of the configuration.ini file, otherwise the tool does not work and returns errors.
Thanks

**Comment by tmeedend** [comment]
Hi! Good to hear someone else is using this tool :) 
I am going to add the requirements!!

Which part of the tool are you using? I am actually using to clean tags of my mods when installing them but I didn't push this for the moment.

**Comment by tmeedend** [comment]
I have changed the documentation. I hope it will help.

**Comment by Noe-Imeji** [comment]
Personally I use this tool to export mods. I need to reinstall on another PC, and it allows me to simply backup all my mods, and keep them on an external drive.
Thank you for the modifications to the description of this tool, I hope it will help other people.
